import { PersonCreateInput } from '@odst/types';

function randomIntFromInterval(min, max) { // min and max included 
  return Math.floor(Math.random() * (max - min + 1) + min)
}

export const TestPersonCreateInput: PersonCreateInput[] = [
  {
    firstName: 'John',
    lastName: 'Doe',
    dodId: randomIntFromInterval(1,9999999999),
    ssn: randomIntFromInterval(1,999999999),
    hairColor: 'BROWN',
    email: String(randomIntFromInterval(1,99999999999)) + '@us.af.mil',
    middleInitial: 'J',
    birthDate: new Date('01/01/2000'),
    birthCity: 'Washington',
    birthCountry: 'USA',
    citizenshipId: '123132',
    grade: 5,
    eyeColor: 'BLUE',
    birthState: 'OR',
    role: 'NONE',
    spec: 'ENLISTED',
    height: 69,
    org: {
      connect: {
        name: 'Scorpion Developers',
      },
    },
  },
  {
    firstName: 'Johnny',
    lastName: 'Toes',
    dodId: 987456789,
    ssn: 567456789,
    hairColor: 'BROWN',
    email: 'Johnny.Toes@us.af.mil',
    middleInitial: 'J',
    birthDate: new Date('01/03/2000'),
    birthCity: 'Washington',
    birthCountry: 'USA',
    citizenshipId: '123156',
    grade: 5,
    eyeColor: 'BLUE',
    birthState: 'CA',
    role: 'NONE',
    spec: 'ENLISTED',
    height: 57,
    org: {
      connect: {
        id: 'hfgjhfjhfmhjfhjmfhfv',
      },
    },
  },
  {
    firstName: 'Tom',
    lastName: 'Sawyer',
    dodId: 3269425899,
    ssn: 111111111,
    eyeColor: 'BLUE',
    birthState: 'OR',
    role: 'NONE',
    spec: 'ENLISTED',
    height: 69,
    hairColor: 'BLACK',
    email: 'tom.sawyer@us.af.mil',
    middleInitial: 'J',
    birthDate: new Date('01/01/1882'),
    birthCity: 'Somewhere',
    birthCountry: 'USA',
    citizenshipId: '123132',
    grade: 7,
    org: {
      connect: {
        id: 'ck3q0xqj0cq0a0129x0x0x0x',
      },
    },
  },
  {
    firstName: 'Imagine',
    lastName: 'Ragon',
    dodId: 5987654321,
    ssn: 222222222,
    hairColor: 'BLONDE',
    eyeColor: 'BLUE',
    birthState: 'OR',
    role: 'NONE',
    spec: 'ENLISTED',
    height: 69,
    email: 'imagine.ragon@us.af.mil',
    middleInitial: 'D',
    birthDate: new Date('01/01/2008'),
    birthCity: 'Nowhere',
    birthCountry: 'USA',
    citizenshipId: '123132',
    grade: 4,
    org: {
      connect: {
        id: 'ck3q0xqj0cq0a0129x0x0x0x',
      },
    },
  },
  {
    firstName: 'Simberly',
    lastName: 'McSim',
    eyeColor: 'BLUE',
    birthState: 'OR',
    role: 'NONE',
    spec: 'ENLISTED',
    height: 69,
    dodId: 3080639307,
    ssn: 333333333,
    hairColor: 'BALD',
    email: 'simberly.mcsim@us.af.mil',
    middleInitial: '',
    birthDate: new Date('04/03/1992'),
    birthCity: 'Anywhere',
    birthCountry: 'USA',
    citizenshipId: '123132',
    grade: 1,
    org: {
      connect: {
        id: 'ck3q0xqj0cq0a0129x0x0x0x',
      },
    },
  },
  {
    firstName: 'Simothy',
    lastName: 'McSim',
    dodId: 3641945755,
    ssn: 111111111,
    eyeColor: 'BLUE',
    birthState: 'OR',
    role: 'NONE',
    spec: 'ENLISTED',
    height: 69,
    hairColor: 'BLACK',
    email: 'simothy.mcsim@us.af.mil',
    middleInitial: 'I',
    birthDate: new Date('30/05/2011'),
    birthCity: 'In There',
    birthCountry: 'USA',
    citizenshipId: '123132',
    grade: 8,
    org: {
      connect: {
        id: 'ck3q0xqj0cq0a0129x0x0x0x',
      },
    },
  },
  {
    firstName: 'Simba',
    lastName: 'John',
    dodId: 3080639307,
    eyeColor: 'BLUE',
    birthState: 'OR',
    role: 'NONE',
    spec: 'ENLISTED',
    height: 69,
    ssn: 444444444,
    hairColor: 'BROWN',
    email: 'simba.john@us.af.mil',
    middleInitial: 'P',
    birthDate: new Date('05/07/2001'),
    birthCity: 'Out There',
    birthCountry: 'Africa',
    citizenshipId: '123132',
    grade: 5,
    org: {
      connect: {
        id: 'ck3q0xqj0cq0a0129x0x0x0x',
      },
    },
  },
  {
    firstName: 'Simbad',
    lastName: 'Ruski',
    dodId: 6199657322,
    eyeColor: 'BLUE',
    birthState: 'OR',
    role: 'NONE',
    spec: 'ENLISTED',
    height: 69,
    ssn: 555555555,
    hairColor: 'BALD',
    email: 'simbad.ruski@us.af.mil',
    middleInitial: 'A',
    birthDate: new Date('24/02/1985'),
    birthCity: 'Simbuktu',
    birthCountry: 'Russia',
    citizenshipId: '123132',
    grade: 3,
    org: {
      connect: {
        id: 'ck3q0xqj0cq0a0129x0x0x0x',
      },
    },
  },
  {
    firstName: 'Simth',
    lastName: 'Jones',
    dodId: 8301616766,
    ssn: 666666666,
    hairColor: 'BLACK',
    eyeColor: 'BLUE',
    birthState: 'OR',
    role: 'NONE',
    spec: 'ENLISTED',
    height: 69,
    email: 'simth.jones@us.af.mil',
    middleInitial: '',
    birthDate: new Date('08/09/2027'),
    birthCity: 'Yourimom',
    birthCountry: 'China',
    citizenshipId: '123132',
    grade: 9,
    org: {
      connect: {
        id: 'ck3q0xqj0cq0a0129x0x0x0x',
      },
    },
  },
];
