trigger:
  - master
  - dev
pr:
  - master
  - dev

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    NX_BRANCH: 'master'
  ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
    NX_BRANCH: $(System.PullRequest.PullRequestNumber)

jobs:
  - job: master
    pool:
      name: Default
      demands:
        - agent.name -equals DOUP-DEVOPS
    condition: ne(variables['Build.Reason'], 'PullRequest')
    steps:
      - script: npm install --global yarn
      - script: yarn
      - script: yarn nx run waypoint-api:prisma-generate
      - script: npx nx affected --base=HEAD~1 --target=test --parallel --max-parallel=3

  - job: pr
    pool:
      name: Default
      demands:
        - agent.name -equals DOUP-DEVOPS
    condition: eq(variables['Build.Reason'], 'PullRequest')
    steps:
      - script: npm install -g yarn
        displayName: Install yarn
      - script: npm install -g nx
        displayName: Install nx
      - script: yarn
        displayName: Install packages
      - script: yarn nx run waypoint-api:prisma-generate
        displayName: Generate Prisma clients
      - script: yarn nx affected --target=test --base=origin/master --head=HEAD --codeCoverage=true --parallel --max-parallel=3
        displayName: Run tests
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/cobertura-coverage.xml'
    


