trigger:
  - master
pr:
  - master

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    NX_BRANCH: 'master'
  ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
    NX_BRANCH: $(System.PullRequest.PullRequestNumber)

jobs:
  - job: master
    pool:
      vmImage: 'ubuntu-latest'
    condition: ne(variables['Build.Reason'], 'PullRequest')
    steps:
      - script: npm i
      - script: npx nx affected --base=HEAD~1 --target=build --parallel --max-parallel=3
      - script: npx nx affected --base=HEAD~1 --target=test --parallel --max-parallel=2

  - job: pr
    pool:
      vmImage: 'ubuntu-latest'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    steps:
      - script: npm i
      - script: npx nx affected --target=build --parallel --max-parallel=3
      - script: npx nx affected --target=test --parallel --max-parallel=2
