trigger:
  - master
pr:
  - master
  - dev

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn  
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    NX_BRANCH: 'master'
  ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
    NX_BRANCH: $(System.PullRequest.PullRequestNumber)


jobs:
  - job: master
    pool:
      name: Default
      demands:
        - agent.name -equals DOUP-DEVOPS
    condition: ne(variables['Build.Reason'], 'PullRequest')
    steps:
      - script: npm install --global yarn
      - script: yarn
      - script: yarn nx run waypoint-api:prisma-generate
      - script: npx nx affected --base=HEAD~1 --target=test --parallel --max-parallel=3

  - job: pr
    pool:
      name: Default
      demands:
        - agent.name -equals DOUP-DEVOPS
    condition: eq(variables['Build.Reason'], 'PullRequest')
    steps:
      - template: ./azure-pipelines/yarn.yml
      - script: yarn nx run waypoint-api:prisma-generate
        displayName: Generate Prisma clients
      - script: yarn nx affected --target=test --base=origin/master --head=HEAD --codeCoverage=true --coverageReporters=text --parallel
        displayName: Run tests
      - script: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:$(Agent.WorkFolder)/**/coverage-cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:'HtmlInline_AzurePipelines;Cobertura'
        displayName: Create code coverage report
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation:  '**/cobertura-coverage.xml'
    


