# Downgraded to 3.7 to ensure it works with non-docker desktop
version: '3.7'

#TODO reuse environment variables (i.e. so database password isn't hardcoded in three different spots)
#TODO figure out how platform team wants to handle environetment variables (like .env.prod)
#TODO add more stuff to be dynamically set - db info, ports, etc

services:
  postgres:
    container_name: postgres
    image: registry1.dso.mil/ironbank/opensource/postgres/postgresql12:latest
    restart: unless-stopped
    #TODO need to map volume for data to stay through container recreation but couldn't get permissions to be happy
    # volumes:
    # - ~/docker/postgres:/var/lib/postgresql
    ports:
      - '5432:5432/tcp'
    environment:
      - POSTGRES_PASSWORD=H@CK3YITPL3ASE
    networks:
      - odst-network

  ods-api:
    container_name: ods-api
    image: ghcr.io/552acns/ods-api:latest
    ports:
      - '3343:3343'
    env_file:
      - apps/ods-api/.env.prod
    depends_on:
      - postgres
    networks:
      - odst-network

  ods:
    container_name: ods
    image: ghcr.io/552acns/ods:latest
    ports:
      - '8080:80'
    depends_on:
      - ods-api
    networks:
      - odst-network

  ods-migrate:
    container_name: prisma-migrate
    image: ghcr.io/552acns/ods-api:prisma
    environment:
      - NX_DATABASE_URL=postgresql://postgres:H@CK3YITPL3ASE@postgres:5432/ods_prod

networks:
  odst-network:
