version: '3.7'
services:
  prisma-migrate:
    container_name: prisma-migrate
    image: ghcr.io/552acns/ods-api:prisma
    environment:
      - NX_DATABASE_URL=postgresql://postgres:H@CK3YITPL3ASE@postgres:5432/ods_prod

    depends_on:
      - postgres
    # restart: on-failure
    networks:
      odst-network:
