# Downgraded to 3.7 to ensure it works with non-docker desktop
version: '3.7'

services:
  postgres:
    container_name: postgres
    image: registry1.dso.mil/ironbank/opensource/postgres/postgresql12:latest
    restart: unless-stopped
    # volumes:
    # - ~/docker/postgres:/var/lib/postgresql
    ports:
      - '5432:5432/tcp'
    environment:
      - POSTGRES_PASSWORD=H@CK3YITPL3ASE
    networks:
      - odst-network

  ods-api:
    container_name: ods-api
    image: ghcr.io/552ACNS/ods-api:latest
    ports:
      - '${PORT:-3343}:${PORT:-3343}'
    env_file:
      - apps/ods-api/.env.prod
    depends_on:
      - postgres
    networks:
      - odst-network

  ods:
    container_name: ods
    image: ghcr.io/552ACNS/ods:latest
    ports:
      - '8080:80'
    depends_on:
      - ods-api
    networks:
      - odst-network

networks:
  odst-network:
