# Downgraded to 3.7 to ensure it works with non-docker desktop
version: '3.7'

services:
  postgres:
    container_name: postgres
    image: registry1.dso.mil/ironbank/opensource/postgres/postgresql12:latest
    ports:
      - '5432:5432/tcp'
    networks:
      - odst-network

  ods-api:
    container_name: ods-api
    build:
      context: .
      dockerfile: ./apps/ods-api/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${PORT:-3343}:${PORT:-3343}'
    depends_on:
      - postgres
    networks:
      - odst-network
  ods:
    container_name: ods
    build:
      context: .
      dockerfile: ./apps/ods/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${PORT:-4210}:${PORT:-4210}'
      - '8080:80'
    depends_on:
      - ods-api
    networks:
      - odst-network

networks:
  odst-network:
