name: CI
on:
  push:
    branches:
      - master
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: false

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [master]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v2 
        with: 
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: npx nx-cloud start-ci-run    
      - run: npx nx affected --target=build --parallel
      - run: npx nx affected --target=test --parallel
      - run: npx nx-cloud stop-all-agents
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: master
      - uses: actions/setup-node@v2
        with: 
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn audit
      - name: Setup .NET 6.x
        uses: actions/setup-dotnet@v1
        with:
          # Semantic version range syntax or exact version of a dotnet version
          dotnet-version: '6.x'
      - name: Generate Prisma clients
        run: npx nx run waypoint-api:prisma-generate
      - run: npx nx affected --target=lint --parallel
      - run: npx nx affected --target=build --parallel
      - run: npx nx affected --target=test  --codeCoverage=true --coverageReporters=cobertura --parallel
      - run: dotnet tool update -g dotnet-reportgenerator-globaltool
        continue-on-error: true
      - name: Report Generator
        run: reportgenerator -reports:**/cobertura-coverage.xml -targetdir:./coverage/merged "-reporttypes:HtmlInline_AzurePipelines;Cobertura"
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: Cobertura.xml # Artifact name        
          path: ./coverage/merged # Directory containing files to upload
