name: CI
on:
  push:
    branches:
      - master
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: false

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout [master]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn audit
  pr:
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'pull_request' }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ods_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: H@CK3YITPL3ASE
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      # - run: yarn audit
      # # - name: Setup .NET 6.x
      # #   uses: actions/setup-dotnet@v1
      # #   with:
      # #     # Semantic version range syntax or exact version of a dotnet version
      # #     dotnet-version: '6.x'
      # - run: yarn nx affected --target=lint --parallel
      # # - run: yarn nx affected --target=test  --codeCoverage=true --coverageReporters=cobertura --parallel
      # - run: yarn nx affected --target=test --parallel
      - name: Migrate postgres database
        run: yarn nx run ods-api:prisma-migrate --skip-generate

      # - name: Cypress run
      #   uses: cypress-io/github-action@v4
      #   with:
      #     project: './apps/ods-e2e'
      #     start: yarn nx serve ods-api
      #     build: yarn nx build ods
      #     wait-on: 'http://localhost:3343/graphql'

      - name: start backend
        run: yarn nx serve ods-api &
      - name: run cypress
        run: yarn nx e2e ods-e2e

      # - name: Run ODS backend
      #   run: yarn nx serve ods-api
      # - name: Run E2E tests
      #   run: ng e2e ods-e2e
      # - run: dotnet tool update -g dotnet-reportgenerator-globaltool
      #   continue-on-error: true
      # - name: Merge Test Coverage Results
      #   run: reportgenerator -reports:**/cobertura-coverage.xml -targetdir:./coverage/merged "-reporttypes:TextSummary;"
      #   continue-on-error: true
      # - name: Upload coverage report artifact
      #   uses: actions/upload-artifact@v2.2.3
      #   with:
      #     path: ./coverage/merged # Directory containing files to upload
