name: docker

on:
  push:
    branches:
      - 'master'
      # - 'dev'
  # pull_request:
  #   branches:
  #     - 'master'
  #     - 'dev'

#TODO is there a way to test if image can be built based on PR code? without doing the whole pipeline. build to first stage w/o pushing?

env:
  REGISTRY: ghcr.io
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
      - name: 'Install nx'
        run: npm i nx --ignore-scripts --legacy-peer-deps --progress=false --audit=false --loglevel=error

      - name: 'nx docker'
        run: npx nx affected --target=docker --push=true
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'nx docker-migrate'
        run: npx nx affected --target=docker-migrate --push=true
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #Ifs to save
    # #region on push: build and push images to registry
    # - name: 'nx docker'
    #   run: npx nx affected --target=docker --push=true
    #   if: ${{ github.event_name != 'pull_request' }}
    #   env:
    #     INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     INPUT_TARGET: deploy

    # - name: 'nx docker-migrate'
    #   run: npx nx affected --target=docker-migrate --push=true
    #   if: ${{ github.event_name != 'pull_request' }}
    #   env:
    #     INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # #endregion

    # #region on PR: only build to first stage
    # - name: 'nx docker'
    #   run: npx nx affected --target=docker
    #   if: ${{ github.event_name == 'pull_request' }}
    #   env:
    #     INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     INPUT_TARGET: build

    # - name: 'nx docker-migrate'
    #   run: npx nx affected --target=docker-migrate
    #   if: ${{ github.event_name == 'pull_request' }}
    #   env:
    #     INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # #endregion
