name: docker

on:
  push:
    branches:
      - 'master'
      # - 'dev'
      - ODST-215-dockerfiles-for-angular-be

env:
  REGISTRY: ghcr.io
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Install Dependencies'
        run: SKIP_POSTINSTALL=1 yarn global add nx --progress=false --audit=false --loglevel=error

      - name: 'nx build'
        run: npx nx affected --target=docker
