name: docker

on:
  push:
    branches:
      - 'master'
      # - 'dev'
      - docker-recreate-images

#TODO set up tags properly (which are currently specified in the nx docker command)
#so that all branches aren't being built to the same tags. I often put other branches as triggers up above,
#since it makes it easy to debug/deploy test images. Which is (currently) bad, since those test images are tagged as production.
#Setting tag bases on current branch would also be a safety net,
#since currently if anyone runs "nx docker" on any branch, it pushes to the tags meant for our real production images

#TODO is there a way to test if image can be built based on PR code? without doing the whole pipeline.
#Could just build images and not push to registry. Or push under a tag based on branch (same as the above TODO)

env:
  REGISTRY: ghcr.io
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=true

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Install Dependencies'
        run: npm i nx --ignore-scripts --legacy-peer-deps --progress=false --audit=false --loglevel=error

      #TODO set image tags automatically based on project version
      - name: 'nx docker'
        run: npx nx affected --target=docker --push=true --tags=${{ steps.meta.outputs.tags }} --labels=${{ steps.meta.outputs.labels }}

      - name: 'nx docker-migrate'
        run: npx nx affected --target=docker-migrate --push=true --tags=${{ steps.meta.outputs.tags }} --labels=${{ steps.meta.outputs.labels }}
