name: docker-ods

on:
  push:
    branches:
      - 'master'
      - 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          registry: ghcr.io
          push: true
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: 552acns/ods:latest
