name: docker

on:
  push:
    branches:
      - 'master'
      - 'dev'

env:
  REGISTRY: ghcr.io
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    # continue-on-error: true

    permissions:
      contents: read
      packages: write

    # strategy:
    #   matrix:
    #     app:
    #       - ods
    #       - ods-api

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: ${{ env.REGISTRY }}/ericcater/${{ matrix.app }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     file: apps/${{ matrix.app }}/Dockerfile
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}

      - name: 'Install Dependencies'
        # TODO slim down what deps are installed?
        run: npm i

      - name: 'nx build'
        run: npx nx affected --target=docker
