name: docker

on:
  push:
    branches:
      - 'master'
      # - 'dev'
      - docker-recreate-images

#TODO set up tags properly (which are currently specified in the nx docker command)
#so that all branches aren't being built to the same tags. I often put other branches as triggers up above,
#since it makes it easy to debug/deploy test images. Which is (currently) bad, since those test images are tagged as production.

#TODO is there a way to test if image can be built based on PR code? without doing the whole pipeline.
#Could just build images and not push to registry. Or push under a tag based on branch (same as the above TODO)

#TODO build docker images to build stage on PR to master as a test?

env:
  REGISTRY: ghcr.io
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - name: 'Install nx'
        run: npm i nx --ignore-scripts --legacy-peer-deps --progress=false --audit=false --loglevel=error

      - name: 'nx docker'
        run: npx nx affected --target=docker --push=true
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'nx docker-migrate'
        run: npx nx affected --target=docker-migrate --push=true
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
